### ISSUE TITLE
Remove from Backend Menu 

### ISSUE THREAD

**Issue by bhargavy** [mplodowski/DynamicPDF#13]
Hello,

In the screen shots and the demo the the PDF Options are inside Settings but on installing the plugin is creating a custom Menu icon. 

Can this be moved back into the settings?

**Comment by mplodowski** [comment]
This has been changed by this PR 33aab15

I think this is a good change. Now you have backend links to templates and layouts separate, so after saving layout you are still on the layouts list.

I see now that we need to adjust permissions for the controllers. You will be able to hide menu icon using permissions for other administrators. I will update plugin soon.

Why do you need this back into the settings?

**Comment by bhargavy** [comment]
I'm building a form in whose preview I intend to show the pdf. Which will require at most 2-3 template's.  Having a menu item for just 3 items seems like a waste of space.

Thanks for the update.
