### ISSUE TITLE
PDF Download

### ISSUE THREAD

**Issue by axomat** [mplodowski/DynamicPDF#14]
Hi
Thanks for the plugin.

I need some help please with how to create a download. I am displaying a web page with a download button. This is executing a method in my component that runs
`        return PDFTemplate::render($templateCode, $data, $params);`
But I want to download rather than display the pdf. Can you help please? Thanks

**Comment by axomat** [comment]
Sorry I can see now that it will automatically download if displayed by a component. I was using an ajax call so that is why it was not downloading.

**Comment by mplodowski** [comment]
In version 2.0 there is a download method. You can check it out. There are some breaking changes, so see upgrade guide how to proceed.

**Comment by axomat** [comment]
Ah that looks a lot better, thanks

**Comment by joebuonocore** [comment]
Hate to bring up again, but can we use an Ajax call to start download after v2? Would prefer if I had a button in my application to download finalized PDF instead of automatically downloading on a confirmation page.
