### ISSUE TITLE
Is there a way to preview layouts and templates as HTML?

### ISSUE THREAD

**Issue by jfoliveira** [mplodowski/DynamicPDF#16]
It would be useful to be able to inspect the HTML/CSS using browser developer tools to experiment with HTML and CSS when creating a new layout or template.

Is there anyway to accomplish that, even programmatically?

**Comment by jfoliveira** [comment]
It seems using the `loadFile` or `loadView` methods I would be able to point to the view while debugging/changing, to inspect its elements, and render the same OctoberCMS view to output the PDF.

Any examples using `loadView` or `loadFile` methods with OctoberCMS?

**Comment by mplodowski** [comment]
I think that this feature can be added to the plugin core. I will add this in the next version.

**Comment by mplodowski** [comment]
Done in version 2.0.1. 

Enable bleeding edge updates if you want to use it right now.

**Comment by jfoliveira** [comment]
Awesome! Outstanding job! Congrats and thank you!
