### ISSUE TITLE
Backend login broken after attempt to install. Error "The Code has already been taken" - 

### ISSUE THREAD

**Issue by jfoliveira** [mplodowski/DynamicPDF#17]
Hi,

Thanks for this great plugin!

On my first attempt to deploy it in production using OctoberCMS `build 345` I could not install the plugin.

The following error message was displayed during the installation process:
```
Update failed

{"#layout-flash-messages":
" <p data-control=\"flash-message\" class=\"flash-message fade error\" 
data-interval=\"5\">The Code has already been taken.<\/p>\n",
"X_OCTOBER_ERROR_FIELDS":{"code":["The Code has already been taken."]}}
```

After that the OctoberCMS backend login is broken with the same error message.

After removing the plugin from the command line:
```
php artisan plugin:remove Renatio.DynamicPDF
```

and delete the `plugins/renatio` folder I made a new attempt to install the plugin with:
```
php artisan plugin:install Renatio.DynamicPDF
```

This time with the following exception is thrown:
```
 [ErrorException]      
  mkdir(): File exists 
```

More details here: https://github.com/octobercms/october/issues/2111 

Any ideas on how to get the plugin working with my current OctoberCMS `build 345`?

**Comment by mplodowski** [comment]
Hi,

I don't know exactly what happened here, I had no issue with deploying this plugin to production server.

First error looks like you had already migrated database, but October tried to do it again for this plugin and validation for unique Code was triggered, when attempting to seed tables.

Second error is the consequence of the first. Probably I will need to add file exists check here to resolve this in the future. For now just remove this folder:

    storage/app/uploads/public/554/28b/6d4

and than run:

    php artisan plugin:remove Renatio.DynamicPDF

then check the database if there are any references to renatio_dynamicpdf tables.

Then try to install plugin again.

**Comment by jfoliveira** [comment]
Hi @mplodowski, removing the folder `storage/app/uploads/public/554/28b/6d4` did the trick and the plugin is now installed and working. Thank you very much!

Another question:
I now have this exception thrown when generating a PDF:
```
exception 'ErrorException' with message:
file_get_contents(/home/forge/my_example_site.com/public/plugins/
renatio/dynamicpdf/assets/fonts/OpenSans-Regular.ttf): 
failed to open stream: No such file or directory
```

I deploy my website using the `php artisan october:mirror` command. See https://octobercms.com/docs/setup/configuration#public-folder

All my own plugins are not copied to the `public` folder and they work fine.
Can you tell me if I should copy the whole `plugin/renation` folder to the `public` folder? Or is there any setting to configure in order to use the plugin with the `october:mirror` command?

**Comment by jfoliveira** [comment]
I found this https://github.com/octobercms/october/issues/1851, so perhaps is not an issue on your end.

I now need to find a way to adjust my nginx settings to point to root folder instead!?

I also asked here https://github.com/octobercms/october/issues/1331 to understand what are the recommended best practices for plugin developers when mirroring to a public folder.

**Comment by mplodowski** [comment]
Sample layout has hardcoded paths to fonts and after mirror command those are no longer available.

Edit your Layout CSS section and change:

    @font-face {
        font-family: 'Open Sans';
        src: url('plugins/renatio/dynamicpdf/assets/fonts/OpenSans-Regular.ttf');
    }

to:

    @font-face {
        font-family: 'Open Sans';
        src: url('assets/fonts/OpenSans-Regular.ttf');
    }

Do this with all font-face references.

Now just copy fonts folder from `plugins/renatio/formbuilder/assets` to your `public/assets` directory.

**Comment by jfoliveira** [comment]
Awesome! Thanks!
As a reference to others with similar issue, I just created a symlink to original folder to make it easier to keep it updated:
```
ln -fns /home/www/my_example_site.com/plugins/renatio/dynamicpdf/assets /home/www/my_example_site.com/public/assets
```

**Comment by dzava** [comment]
You don't have to create the symlink manually just run the mirror command after you install the plugin.

**Comment by jfoliveira** [comment]
@dzava It worked! I was not aware of that. Even better this way. Thank you very much!
