### ISSUE TITLE
Too much recursion

### ISSUE THREAD

**Issue by joebuonocore** [mplodowski/DynamicPDF#22]
With DynamicPDF installed: updating system, plugins, or logging into the backend of October throws a "Too much recursion" error. Can't seem to narrow down. As soon as I uninstall DynamicPDF, error goes away. Any thoughts?

**Comment by mplodowski** [comment]
Hi,

this error occurs when October try to install dependencies from other plugins. But my plugin does not have any, so it is very interesting.

Try to update October first without DynamicPDF and after that try to install it.

What other plugins do you have installed?

**Comment by joebuonocore** [comment]
You are very wise, and I am very wrong!

I'm running DynamicPDF with two plugins I've created for a client's application. Set require statement in both to require PDF. Removed the require statement, issue gone.

Forgot uninstall would then "disable" my plugins, making it appear as if Dynamic was the cause.

Appreciate your guidance and exceptionally useful plugin. Cheers.
