### ISSUE TITLE
Embedding images into template

### ISSUE THREAD

**Issue by MilosStanic** [mplodowski/DynamicPDF#23]
First, I noticed it is not really possible to call an image from October resources with something like

```
<img src="{{ 'path_to_image/image.jpg'|theme }}">
```
which is a pity. 

I needed to put a logo on my invoice template, but not as a whole background image, so I put my logo image in the body like:

```
<div class="header">
            <p class="left"><img src="{{ background_img}}"></p>
```
And it was visible in the HTML preview, but it reported "unknown type or image not found" in PDF. 
After browsing google and stackoverflow, I took the absolute url of the image like this:

```
<img src="./storage/app/uploads/public/581/b8d/a3e/581b8da3ef870347781077.png">
```

Now, when there is no dot "./" at the beginning, the image is visible in the HTML preview, but not in PDF preview, but when I put the dot, it is not visible in the HTML preview, but visible in the PDF preview.

**Comment by mplodowski** [comment]
Yeah `theme` filter is not available in backend. I assume that it is registered only in CMS section on frontend.

Try something like this:

    <img src="{{ 'storage/app/uploads/public/581/b8d/a3e/581b8da3ef870347781077.png'|app }}">

**Comment by devmnrj** [comment]
I have tried your solution:

<img src="{{ 'storage/app/uploads/public/581/b8d/a3e/581b8da3ef870347781077.png'|app }}">

But when I Preview it as PDF, I get :

file_put_contents(): Filename cannot be empty

/Applications/XAMPP/xamppfiles/htdocs/projects/mizzouadvantagecod/plugins/renatio/dynamicpdf/vendor/dompdf/dompdf/src/Image/Cache.php line 113

**Comment by mplodowski** [comment]
@devmnrj it is logical that you will run into error. I used data from @MilosStanic post. You don't have image with path `storage/app/uploads/public/581/b8d/a3e/581b8da3ef870347781077.png` in your project. Just use valid image path that exists in you installation.
