### ISSUE TITLE
 OctoberCMS Renatio.DynamicPDF 

### ISSUE THREAD

**Issue by cogitologue** [mplodowski/DynamicPDF#26]
Error when I click on Preview Pdf button
![image](https://cloud.githubusercontent.com/assets/7788771/23366206/3ecfc0c2-fd06-11e6-85b9-a90383c66ef1.png)

**Comment by mplodowski** [comment]
https://github.com/barryvdh/laravel-dompdf/issues/190

This is third-party issue. It should be already fixed. 

Please run `composer update` in project directory to update all dependencies.
