### ISSUE TITLE
Relationship..how?

### ISSUE THREAD

**Issue by Asinox** [mplodowski/DynamicPDF#27]
Hey guys thank you for this great plugin.

I have a question...
How i can use my model relationship?

For example:

 ```
public $attachMany = [
    	'images' => ['System\Models\File', 'public'=>true]
 ];
```
This is not working: {{images}}

Any idea?

Thank you!

**Comment by mplodowski** [comment]
Before you can use any data in pdf template you must first grab it and pass it to PDF function. Plugin does not know anything about your models or relations.

For example I assume that you have `Post` model with `images` relation.

Grab model record:

```
$post = Post::first();
```

Next pass `$post` to PDF function:

```
$templateCode = 'renatio::invoice';

return PDF::loadTemplate($templateCode, compact('post'))->stream();
```

In PDF template you can access post with images using `for` loop like so:

```
{% for image in post.images %}
    {{ image.getPath }}
{% endfor %}
```

**Comment by Asinox** [comment]
@mplodowski  thank for you reply... sure that im passing the data to PDF function (just i don't want to put all that code here)...i did before to ask like you said, but nothing happens, let me try one more time.

Thank you

**Comment by mplodowski** [comment]
If you still need help than you should paste your code how you generate PDF and your PDF template.
