### ISSUE TITLE
Request Headers updating but no pdf

### ISSUE THREAD

**Issue by virtualLast** [mplodowski/DynamicPDF#29]
Hello,

Im calling a function to generate the PDF, via an ajax call to a function. That function pulls in data ready to pass to the pdf template file. When the button is clicked I can see that the request headers are updating however there is no pdf being output either using download() or stream()

I have the below in a component class
`    public function onGeneratePDF()
    {

        $model = new ProductType();
        $templateCode = 'technical-data-sheet'; // unique code of the template
        $this->data = ['name' => 'John Doe'];

        return PDF::loadTemplate($templateCode, $this->data)->download();

    }`
and this in a component partial
`<a href="" data-request="{{__SELF__}}::onGeneratePDF" target="_blank">PDF</a>`

I am running php 7.1 so I updated dompdf to version 0.8.0

**Comment by mplodowski** [comment]
OctoberCMS ajax framework cannot handle this type of response.

Read this: https://github.com/octobercms/october/issues/2182

Recommended approach is to save PDF file locally and return redirect to PDF file.

**Comment by virtualLast** [comment]
Hi that is the way I decided to go after testing a few other things out.

**Comment by maartenmachiels** [comment]
Hi, does anyone have a code example? 

I'm trying to generate a PDF via a button in the backend of the update page of a model. The button uses the October CMS AJAX framework and calls a function onGeneratePDF in the controller file. 

I tried:

```
        $path = 'storage/app/media/'.$file.'.pdf';
        $saved = PDF::loadTemplate($templateCode, $data)->save($path);
        $headers = [
            'HTTP/1.1 200 OK',
            'Pragma: public',
            'Content-Type: application/pdf'
        ];
        return Response::download(base_path($path), $file.'.pdf', $headers)->deleteFileAfterSend(true);
```
This does generate the file (and clears it), but it does not show it to the browser. 

The following

`return Redirect::to('storage/app/media/'.$file.'.pdf');`

... does work, but it has the disadvantage that the file stays on the server and this is not intended. The PDF contains private information and should not be available via a URL.

What is the right way to tackle this?

**Comment by mplodowski** [comment]
Read documentation:

https://github.com/mplodowski/dynamicpdf-plugin#tip-download-pdf-via-ajax-response

If you just want to stream PDF, than just create normal method in controller:

https://github.com/mplodowski/dynamicpdf-plugin#render-pdf-in-browser

**Comment by maartenmachiels** [comment]
I wouldn't ask a question without reading the docs... I solved it in a different way, via an attachOne relation to my model and redirecting to that.
