### ISSUE TITLE
PDF in CMS page

### ISSUE THREAD

**Issue by snipiba** [mplodowski/DynamicPDF#3]
Hi,

how to set pdf response to get PDF on CMS PAGE, where is defined function onInit?

**Comment by mplodowski** [comment]
Hi,

in CMS Page, in **Code** section paste this code:

    use Renatio\DynamicPDF\Models\PDFTemplate;

    function onStart()
    {
        $templateCode = 'renatio::invoice';
        $data = ['name' => 'John Doe'];

        return PDFTemplate::render($templateCode, $data);
    }

Remember to change **templateCode** and pass your data to render function if you have any. 

If this is static pdf you can ommit $data parameter.

**Comment by batturmng** [comment]
how to use $data in template. {{data.name}} or how to do? sorry my bad english

**Comment by Asinox** [comment]
@batturmng  like this: {{name}} just that

**Comment by qroft** [comment]
Man, THIS issue is IMHO so important for this plugin! I have just been asking myself on how to create an OctoberCMS DB query and get the result shown on my PDF. This is exactly what  i needed and think that it should be mentioned somewhere in the documentation for noobs like me!
