### ISSUE TITLE
Error in vendor file

### ISSUE THREAD

**Issue by abelschooleman** [mplodowski/DynamicPDF#30]
Hi guys, I'm getting this error from one of the vendor files

`A non-numeric value encountered
/Users/abel/Sites/myboilie/plugins/renatio/dynamicpdf/vendor/dompdf/dompdf/src/Positioner/Fixed.php line 56`

**Comment by mplodowski** [comment]
There is an issue with PHP 7.1 and dompdf.

https://github.com/barryvdh/laravel-dompdf/issues/294

Try to update composer and use version 0.8

```
{
  "require": {
    "barryvdh/laravel-dompdf": "0.8.*",
    "illuminate/contracts" : "5.1.*",
    "illuminate/support" : "5.1.*"
  }
}
```

Let me know if this fix works.

**Comment by abelschooleman** [comment]
Good stuff, that was it! Thanks!

**Comment by vojtasvoboda** [comment]
Same error here with PHP 7.1. Are you going to update laravel-dompdf 0.8 directly in plugin?

**Comment by mplodowski** [comment]
Yes, I just push the update.

**Comment by vojtasvoboda** [comment]
👍
