### ISSUE TITLE
Can you provide an example how to set paper size?

### ISSUE THREAD

**Issue by abelschooleman** [mplodowski/DynamicPDF#31]
I'm trying to set a custom paper size for printing a sticker but I can't manage to change the size. I understand I need the setPaper method but I'm just getting the default A4 size. Also, trying a different standard paper size, available in [CPDF.php](https://github.com/dompdf/dompdf/blob/master/src/Adapter/CPDF.php) returns A4.

`PDF::setPaper([0,0,164,187], 'portrait');`
`return PDF::loadTemplate('myboilie.orders::nl.sticker', $data)->stream();`

**Comment by mplodowski** [comment]
Something like this should work:

```
return PDF::loadTemplate('myboilie.orders::nl.sticker', $data)
    ->setPaper([0,0,164,187], 'portrait')
    ->stream();
```

**Comment by abelschooleman** [comment]
Ah, chaining...didn't try that. This works, thanks again!
