### ISSUE TITLE
Open_basedir restriction

### ISSUE THREAD

**Issue by vojtasvoboda** [mplodowski/DynamicPDF#32]
Hi there, thanks for the great plugin. I'm getting this issue on some hosting (not every):

`exception 'ErrorException' with message 'file_exists(): open_basedir restriction in effect. File(/tmp//log.htm) is not within the allowed path(s): (/usr/local/www/data/:/var/tmp)' in /usr/local/www/data/mysite.cz/www/plugins/renatio/dynamicpdf/vendor/dompdf/dompdf/src/Dompdf.php:699`

In my User export PDF plugin I fixed that by explicit setting of `logOutputFile`: https://github.com/vojtasvoboda/oc-userexportpdf-plugin/commit/34e07dd0dddddd8ff1b3afadcfc873f2e8d8a5c3

But when I'm using only your plugin separately, I'm having same error when I click on PDF template > Preview.

So I just want to let you know.

**Comment by mplodowski** [comment]
Thanks for heads up. I added this to the plugin code.

https://github.com/mplodowski/DynamicPDF/commit/9645cc099320bf88445fd3701b0505b2cbca531b
