### ISSUE TITLE
Force download via AJAX

### ISSUE THREAD

**Issue by rajakhoury** [mplodowski/DynamicPDF#39]
Hi,
I am wondering why the file won't download during an ajax call, in my component ;

    public function onExportPDF(){
	  return PDF::loadTemplate('renatio::invoice')->download();
    }

The response is always returned as a string - Response headers ;

Cache-Control:no-cache
Connection:Keep-Alive
Content-Disposition:attachment; filename="document.pdf"
Content-Type:application/pdf
Date:Mon, 17 Jul 2017 02:54:26 GMT
Keep-Alive:timeout=5, max=100
Server:Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.1.4
Transfer-Encoding:chunked
X-Powered-By:PHP/7.1.4

**Comment by mplodowski** [comment]
Hi,

check this topic: https://github.com/mplodowski/DynamicPDF/issues/29

**Comment by rajakhoury** [comment]
I end up create an export page and component to make it work then in `onRun` method  added;
 
    if( $this->export ){
	   return PDF::loadTemplate('renatio::invoice')->download();
    }
