### ISSUE TITLE
Class 'Barryvdh\DomPDF\ServiceProvider' not found

### ISSUE THREAD

**Issue by dunets** [mplodowski/DynamicPDF#43]
After installing on server, I have and error ````Class 'Barryvdh\DomPDF\ServiceProvider' not found````

![image](https://user-images.githubusercontent.com/6217617/28970558-e0862a6e-7920-11e7-95f5-6674b2b91336.png)

How I can solve that problem?

**Comment by dunets** [comment]
Solution:
its necesary to install dompdf by running these command:
 `composer require barryvdh/laravel-dompdf`

**Comment by mplodowski** [comment]
https://github.com/mplodowski/dynamicpdf-plugin/issues/46
