### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by 1130709** [mplodowski/DynamicPDF#45]
Hello,

After installing the plugin from the backend this error shows up:

"Class 'Barryvdh\DomPDF\ServiceProvider' not found"

What can I do?

**Comment by mplodowski** [comment]
You must go to this plugin directory `/plugins/renatio/dynamicpdf/` and run `composer install` command.

This should be done automatically by OctoberCMS installer, so something went wrong when you installed this plugin. Maybe try to reinstall it.

**Comment by mplodowski** [comment]
Duplicate https://github.com/mplodowski/dynamicpdf-plugin/issues/46
