### ISSUE TITLE
chinese characters become ???

### ISSUE THREAD

**Issue by ran-tw** [mplodowski/DynamicPDF#5]
chinese characters become ???
I tried to set the utf-8 meta but still didn't work.
maybe it's setfont problem

**Comment by mplodowski** [comment]
Hi,

in layout specify: 

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

In CSS section remove all @font-face declarations from default layout and replace them with this:

    @font-face {
        font-family: 'Noto Sans';
        font-style: normal;
        font-weight: 400;
        src: url(http://eclecticgeek.com/dompdf/fonts/cjk/fireflysung.ttf) format('truetype');
    }
    
    body {
        font-family: Noto Sans, sans-serif;
        font-size: 13px;
    }

Now reload pdf. First time will load couple of seconds, because it has to download new font and parse it.

**Comment by ran-tw** [comment]
Hello mplodowski,
I get a error after download complete. :disappointed: 
<pre>strftime() expects parameter 2 to be integer, float given</pre>

**Comment by mplodowski** [comment]
This error looks like Twig error. You probably have syntax error in your pdf template.

Just use plain text in your template to check if this is the case.
