### ISSUE TITLE
Error when previewing pdf template

### ISSUE THREAD

**Issue by mosid** [mplodowski/DynamicPDF#6]
I get this error when trying to preview the provided template
![pdf](https://cloud.githubusercontent.com/assets/5040354/12535390/9bbb754c-c292-11e5-8ca6-7a94546fafba.png)

october v 313
php 5.5.28
windows 8

**Comment by mplodowski** [comment]
This domPDF issue: https://github.com/dompdf/dompdf/issues/1027

Try to replace all IDs in template and layout with classes. You must also edit css to reflect your changes.

I will soon update plugin and do the same.
